---
# tasks file for antoniounir.configuracionK8sMaster
- include_tasks: playbookMaster.yml
- include_tasks: playbookSDN.yml
- include_tasks: playbookIngressController.yml
#- include_tasks: playbookUserNoAdmin.yml