---
    #https://stackoverflow.com/questions/41887491/python-usage-of-crypt-function
    #Hay que generar el pass cifrado ya que el modulo user de ansible asi lo requiere  
    # Dado python 3 esta instalado en la maquina se puede utilizar
  - name: Generate Pass
    shell: python3 -c 'import crypt,sys;print(crypt.crypt("{{pass_cluster}}", crypt.mksalt(crypt.METHOD_SHA512)))'
    register: generatePass

    # Se crea el usuario y se añade al grupo wheel
  - name: Crear usuario
    user:
       name: '{{user_cluster}}'
       comment: Usuario gestion cluster kubernetes
       home: '/home/{{user_cluster}}'
       group: wheel
       state: present
       generate_ssh_key: yes
       ssh_key_bits: 2048
       password: '{{generatePass.stdout}}'


  - name: Creacion Directorio 
    file:
      path: '/home/{{user_cluster}}/.kube'
      state: directory
    register: outMk

  - debug: var=outMk

  - name: Autorizar a {{user_cluster}} acceso al cluster --> Copiar admin.conf
    copy:
       src: /etc/kubernetes/admin.conf
       dest: '/home/{{user_cluster}}/.kube/config'
       remote_src: yes


  - name: Autorizar a {{user_cluster}} acceso al cluster --> Permisos
    shell: chown {{user_cluster}}. /home/{{user_cluster}}/.kube/config


  - name: Configuracion repositorio kubernetes
    lineinfile:
        path: '/etc/sudoers.d/{{user_cluster}}'
        line: '{{item}}'
        state: present
        create: yes
    with_items:
       - 'ALL            ALL = (ALL) NOPASSWD: ALL'

      