---
# Tareas para la creacion de un usuario que pueda gestionar el clúster de Kubernetes sin tener que ser root
# Tareas forman parte del rol antoniounir.configuracionK8sMaster
# Revisar el fichero de variables a configurar para este rol(roles\antoniounir.configuracionK8sMaster\vars\main.yml)
# Tareas a realizar:
# - Generar el pass cifrado del usuario. Módulo shell de Ansible
#   El módulo user de Ansible requiere que el password vaya cifrado
#   Ya que en las maquinas esta instalado python3 me decanto por la opcion de usar el modulo crypt de pythos
#   https://stackoverflow.com/questions/41887491/python-usage-of-crypt-function
# - Crear el usuario.Módulo user de Ansible
# - Crear el directorio .kube en el directorio del usuario creado. Módulo file de Ansible
# - Autorizar al usuario creado acceso al cluster.Copiar el fichero /etc/kubernetes/admin.conf al home/usuario/.kube/config.Módulo copy de Ansible
# - Autorizar al usuario creado acceso al cluster.Otorgar Permisos.Módulo shell de Ansible
  - name: Generate Pass
    shell: python3 -c 'import crypt,sys;print(crypt.crypt("{{pass_cluster}}", crypt.mksalt(crypt.METHOD_SHA512)))'
    register: generatePass

    # Se crea el usuario y se añade al grupo wheel
  - name: Crear usuario
    user:
       name: '{{user_cluster}}'
       comment: Usuario gestion cluster kubernetes
       home: '/home/{{user_cluster}}'
       group: wheel
       state: present
       generate_ssh_key: yes
       ssh_key_bits: 2048
       password: '{{generatePass.stdout}}'


  - name: Creacion Directorio 
    file:
      path: '/home/{{user_cluster}}/.kube'
      state: directory
    register: outMk

  - debug: var=outMk

  - name: Autorizar a {{user_cluster}} acceso al cluster --> Copiar admin.conf
    copy:
       src: /etc/kubernetes/admin.conf
       dest: '/home/{{user_cluster}}/.kube/config'
       remote_src: yes


  - name: Autorizar a {{user_cluster}} acceso al cluster --> Permisos
    shell: chown {{user_cluster}}. /home/{{user_cluster}}/.kube/config


  - name: Configuracion repositorio kubernetes
    lineinfile:
        path: '/etc/sudoers.d/{{user_cluster}}'
        line: '{{item}}'
        state: present
        create: yes
    with_items:
       - 'ALL            ALL = (ALL) NOPASSWD: ALL'
