---
# Tareas para la instalacion de un ingress controller (En nuestro caso HaProxy)
# Tareas forman parte del rol antoniounir.configuracionK8sMaster
# Revisar el fichero de variables a configurar para este rol(roles\antoniounir.configuracionK8sMaster\vars\main.yml)
# Tareas a realizar:
# - Instalar el ingress controller. Módulo command de Ansible
  - name: Instalacion Ingress Controller (HaProxy)
    command: kubectl apply -f "{{ ingress_controller_ulr }}"


  - name: Verificacion namespaces  
    shell: kubectl get namespaces && kubectl get pods --namespace=haproxy-controller
    register: verificacionNamespacesIngress

  - debug: var=verificacionNamespacesIngress


  - name: Verificacion pods para namespace haproxy-controller
    shell: kubectl get pods --namespace=haproxy-controller
    register: verificacionPods

  - debug: var=verificacionPods


  - name: Verificacion Servicios
    command: kubectl get svc -A
    register: veriticacionServicios

  - debug: var=veriticacionServicios
