---
# vars file for antoniounir.configuracionK8sMaster
# Variables necesarias para las tareas del rol antoniounir.configuracionK8sMaster
#     PODs_red --> CIDR para la red de PODs                                               Ejemplo --> PODs_red: 192.169.0.0/16
#     ingress_controller_ulr --> Url donde se encuentra el ingress controller(haproxy)    Ejemplo --> ingress_controller_ulr: 'https://raw.githubusercontent.com/haproxytech/kubernetes-ingress/v1.5/deploy/haproxy-ingress.yaml'
#     tigera_url --> Url donde se encuentra el operador (en nuestro caso tigera)          Ejemplo --> tigera_url: 'https://docs.projectcalico.org/manifests/tigera-operator.yaml'
#     calico_url --> Url donde se encuentra la SDN (en nuestro caso calico)               Ejemplo --> calico_url: 'https://docs.projectcalico.org/manifests/custom-resources.yaml'
#     user_cluster --> Identificador del usuario a crear para gestionar el clúster        Ejemplo --> user_cluster: kubeadmin
#     pass_cluster --> Password del usuario a crear para gestionar el clúster             Ejemplo --> pass_cluster: kubeadmin
PODs_red: 192.169.0.0/16
ingress_controller_ulr: 'https://raw.githubusercontent.com/haproxytech/kubernetes-ingress/v1.5/deploy/haproxy-ingress.yaml' 
tigera_url: 'https://docs.projectcalico.org/manifests/tigera-operator.yaml'
calico_url: 'https://docs.projectcalico.org/manifests/custom-resources.yaml'
user_cluster: kubeadmin
pass_cluster: kubeadmin