---
# Tareas para la configuracion común a los nodos master y workers del clúster de Kubernetes
# Tareas forman parte del rol antoniounir.configuracionK8sMasterWorkers
# Revisar el fichero de variables a configurar para este rol(roles\antoniounir.configuracionK8sMasterWorkers\vars\main.yml)
# Tareas a realizar:
# - Permitir resoluxion DNS, añadiendo las ips de los nodos al fichero /etc/hosts. Módulo lineinfile de Ansible
# - Activar Trasparent Masquerade (modProbe). Módulo command de Ansible
# - Activar Trasparent Masquerade (Firewall). Módulo firewalld de Ansible
# - Recargar el firewall tras la activacion del masquerade. Módulo systemd de Ansible
# - Configurar k8s.conf.Trafico cortafuegos. Módulo lineinfile de Ansible
# - Desactivar Swap. Módulo command de Ansible
# - Eliminar Swap en el arranque (etc/fstab).Módulo lineinfile de Ansible
# - Establecer repositorio de docker. Módulo command de Ansible
# - Instalar Docker. Módulo dnf de Ansible
# - Iniciar Docker. Módulo service de Ansible
# - Instalar Kubernetes. Módulo dnf de Ansible
# - Iniciar Kubernetes. Módulo service de Ansible
  - name: Resolucion DNS (etc/hosts)
    lineinfile:
        path: /etc/hosts
        line: "{{item.ip}} {{item.hostname}}"
        state: present
        create: yes
    with_items:
       - "{{ (hostvars[inventory_hostname]['direcciones_ip']) }}"


  - name: Activar Trasparent Masquerade (modProbe)
    command: modprobe br_netfilter


  - name: Activar Trasparent Masquerade (Firewall)
    firewalld:
      masquerade: yes  
      permanent: yes
      immediate : yes
      state: enabled


  - name: Recarga Configuracion Firewall Masquerade
    systemd:
      name: firewalld
      state: reloaded



  - name: Kubernetes trafico cortafuegos(k8s.conf)
    lineinfile:
        path: /etc/sysctl.d/k8s.conf
        line: "{{item}}"
        state: present
        backup: yes
        create: yes
    with_items:
       - 'net.bridge.bridge-nf-call-ip6tables = 1'
       - 'net.bridge.bridge-nf-call-iptables = 1'


  - name: Servicios
    command: sysctl --system
    register: systemctl_system


  - name: Visualizar systemctl --system
    debug:
       msg : "{{systemctl_system.stdout}}"


  - name: Desactivar SWAP
    command: swapoff -a


  - name: Eliminar arranque SWAP (etc/fstab)
    lineinfile:
        path: /etc/fstab
        regexp: "/cl-swap"
        state: absent
        backup: yes


  - name: Establecimiento repositorio de Docker
    command:
       cmd: dnf config-manager --add-repo="{{ (docker_repo) }}" 
       warn: no


  - name: Instalacion de Docker
    dnf:
        name: ["docker-ce","containerd.io"]
        state: present  


  - name: Iniciar de Docker
    service: 
      name: docker
      enabled: yes
      state: started


  - name: Configuracion repositorio kubernetes
    lineinfile:
        path: /etc/yum.repos.d/kubernetes.repo
        line: "{{item}}"
        state: present
        backup: yes
        create: yes
    with_items:
       - "[kubernetes]"
       - "name=Kubernetes"
       - "baseurl={{ kubernetes_baseurl }}"
       - "enabled=1"
       - "gpgcheck=1"
       - "repo_gpgcheck=1"
       - "gpgkey={{ kubernetes_gpgkey }}"
       - "exclude=kubelet kubeadm kubectl"


  - name: Instalacion de Kubernetes
    dnf:
        name: ['kubelet','kubeadm','kubectl']
        state: present
        disable_excludes : kubernetes


  - name: Inicio de Kubernetes
    service: 
      name: kubelet
      enabled: yes
      state: started

