---

  - name: Reset kubeadm
    command: kubeadm reset -f


  - name: Configuracion Firewall workers Kubernetes
    firewalld:
       zone: public
       port: "{{item}}"
       permanent: yes
       immediate : yes
       state: enabled
    with_items:
       - "10250/tcp"
       - "30000-32767/tcp"


  - name: Recarga Configuracion Firewall workers Kubernetes
    systemd:
      name: firewalld
      state: reloaded


  - name: Copia el fichero con el comando de union al cluster a los workers
    copy: src=./joinCommand dest=./joinCommand  


  - name: Union de worker al cluster (Obtencion comando desde fichero ./joinCommand)
    shell: cat ./joinCommand 
    register: join_command

  - name: Union de worker al cluster (Ejecucion de comando "{{join_command}}")
    shell: "{{join_command.stdout}}"  


