---
# Tareas para la configuracion de los nodos worker del clúster de Kubernetes
# Tareas forman parte del rol antoniounir.configuracionK8sMaster
# Revisar el fichero de variables a configurar para este rol(roles\antoniounir.configuracionK8sMaster\vars\main.yml)
# Tareas a realizar:
# - Reset de kubeadm. Módulo command de Ansible
#   Lo utilizo pq, en ocasiones, tenia problemas con puertos abiertos
# - Abrir los puertos necesarios en el firewal. Módulo firewalld de Ansible
# - Recargar el firewall tras la apertura de puertos.Módulo systemd de Ansible
# - Copiar el fichero generado al configurar el master (./joinCommand) del Ansible Controller a los workers
#   Este fichero tiene la url de union al master
# - Unir los workers al master
#   Para ello se hace manda el contenido del fichero a una variable
  - name: Reset kubeadm
    command: kubeadm reset -f


  - name: Configuracion Firewall workers Kubernetes
    firewalld:
       zone: public
       port: "{{item}}"
       permanent: yes
       immediate : yes
       state: enabled
    with_items:
       - "10250/tcp"
       - "30000-32767/tcp"


  - name: Recarga Configuracion Firewall workers Kubernetes
    systemd:
      name: firewalld
      state: reloaded


  - name: Copia el fichero con el comando de union al cluster a los workers
    copy: src=./joinCommand dest=./joinCommand  


  - name: Union de worker al cluster (Obtencion comando desde fichero ./joinCommand)
    shell: cat ./joinCommand 
    register: join_command

  - name: Union de worker al cluster (Ejecucion de comando "{{join_command}}")
    shell: "{{join_command.stdout}}"  


