---

  - name: Hacer ping a las maquina
    ping:


  - name: Actualizacion de las maquina
    dnf:
       name: "*"
       state: latest


  - name: Sincronizacion Horaria
    shell: timedatectl set-timezone Europe/Madrid && timedatectl set-ntp true


  - name: Desactivar SELinux
    command:
       cmd: sed -i s/=enforcing/=disabled/g /etc/selinux/config
       warn: no


  - name: Instalaciones (NFS-UTILS,NFS4-ACL-TOOLS,WGET,PYTHON3...)
    dnf:
        name: ['chrony','python3','nfs-utils','nfs4-acl-tools','wget']
        state: latest


  - name: Activar Chrony
    service: 
      name: chronyd
      enabled: yes
      state: started



  - name: Actualizacion de las maquina
    dnf:
       name: "*"
       state: latest


  - name: Reboot
    reboot:
