all:
  vars:
    ansible_python_interpreter: '/usr/bin/python3'
    direcciones_ip:
       - {"name": KubernetesMaster, "ip":192.168.1.70, "url":master.local}
       - {"name": KubernetesNode1,"ip":192.168.1.71, "url":node1.local}
  children:
     Kubernetes_Master:
      hosts:
       KubernetesMaster:
         ansible_host: '{{direcciones_ip[0].ip}}'
         ansible_user: ansible
     Kubernetes_Nodes:
      hosts:
       KubernetesNode1:
         ansible_host: '{{direcciones_ip[1].ip}}'
         ansible_user: ansible
     NFS:
      hosts:
       KubernetesNode1:
         ansible_host: '{{direcciones_ip[1].ip}}'
         ansible_user: ansible

