all:
  vars:
     ansible_python_interpreter: '/usr/bin/python3'
     direcciones_ip:
        - {"name": KubernetesMaster, "ip":40.114.236.156, "hostname":master.azure}
        #- {"name": KubernetesNFS, "ip":40.114.194.89, "hostname":nfs.azure}  Debido a limitaciones de la cuenta de Azure y a que master de kubernetes requiere al menos 2 CPU
        - {"name": KubernetesNode1, "ip":13.80.106.146, "hostname":nodo1.azure}
        #- {"name": KubernetesNode2, "ip":13.94.192.103, "hostname":nodo2.local}
  children:
     Kubernetes_Master:
      hosts:
       KubernetesMaster:
         ansible_host: '{{direcciones_ip[0].ip}}'
         ansible_user: adminUsername
     Kubernetes_Nodes:
      hosts:
       KubernetesNode1:
         ansible_host: '{{direcciones_ip[1].ip}}'
         ansible_user: adminUsername
      # KubernetesNode2:
      #   ansible_host: '{{direcciones_ip[3].ip}}'
      #   ansible_user: adminUsername
     NFS:
      hosts:
       KubernetesMaster:
         ansible_host: '{{direcciones_ip[0].ip}}'
         ansible_user: adminUsername

