- hosts: Kubernetes_Nodes
  order: sorted
  gather_facts: true
  become: true
  vars: 
        join_command: 'kubeadm join 192.168.1.70:6443 --token r55qqk.digm7z5pv85d5gjr     --discovery-token-ca-cert-hash sha256:e587e7fe5039fd5730762a517aa693ef3befad907021ec630a8587d207d10867'

  tasks:
  - name: Comando de union al cluster
    debug:
       msg: "{{join_command}}"


  #- name: Union de worker al cluster con gestion de error
  #  block:
       #- name: Union de worker al cluster
       #  command: "{{join_command}}"
  #  rescue:
       #- name: Reset
       #  command: kubeadm reset -f
       
  - name: Union de worker al cluster
    command: "{{join_command}} --v=6"
    
