---
#Tareas comunes a realizar en el master y los workers
- hosts:all
  order: sorted
  gather_facts: yes
  become: true

  tasks:
  - name: Activar Trasparent Masquerade
    shell: modprobe br_netfilter && firewall-cmd --add-masquerade --permanent && firewall-cmd --reload
 
 
  - name: Kubernetes trafico cortafuegos(k8s.conf)
    lineinfile:
        path: /etc/sysctl.d/k8s.conf
        line: "{{item}}"
        state: present
        create: yes
    with_items:
       - 'net.bridge.bridge-nf-call-ip6tables = 1'
       - 'net.bridge.bridge-nf-call-iptables = 1'


  - name: Kubernetes trafico cortafuegos(k8s.conf) 3
    command: sysctl --system


  - name: Desactivar SWAP
    command: swapoff -a


  - name: Eliminar arranque SWAP (etc/fstab)
    lineinfile:
        path: /etc/fstab
        regexp: '\cs-swap'
        state: absent
        backup: yes


  - name: Instalacion de Docker
    shell: dnf config-manager --add-repo="{{ (hostvars[inventory_hostname]['docker_repo']) }}" && dnf install "{{ (hostvars[inventory_hostname]['docker']) }}" -y && systemctl enable docker && systemctl start docker


  - name: Configuracion repositorio kubernetes
    lineinfile:
        path: /etc/yum.repos.d/kubernetes.repo
        line: "{{item}}"
        state: present
        create: yes
    with_items:
       - "[kubernetes]"
       - "name=Kubernetes"
       - "baseurl={{ (hostvars[inventory_hostname]['kubernetes_baseurl']) }}"
       - "enabled=1"
       - "gpgcheck=1"
       - "repo_gpgcheck=1"
       - "gpgkey={{ (hostvars[inventory_hostname]['kubernetes_gpgkey']) }}"
       - "exclude=kubelet kubeadm kubectl"


  - name: Instalacion, Activacion e Inicio de Kubernetes
    shell: dnf install -y kubelet kubeadm kubectl --disableexcludes=kubernetes && systemctl enable kubelet && systemctl start kubelet
